// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DownloadPlaylist(arg1:string):Promise<string>;

export function GetConfig():Promise<models.Config>;

export function SelectFolder():Promise<string>;

export function UpdateConfig(arg1:models.Config):Promise<string>;
