// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadPlaylist(arg1) {
  return window['go']['main']['App']['DownloadPlaylist'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
